### ISSUE TITLE
Error connet to DevTools Protocol

### ISSUE THREAD

**Issue by RoccoNatuzzi** [JoakimCh/grok-archiver#2]
I have this issue when lunching command:
Connecting to the Chrome DevTools Protocol...
(node:24712) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Could not connect. This usually means that your browser was already running (but without having the CDP port set). If that's the case just close it and run this program again, it will then launch it for you with the correct CDP port configured.

Config file:
"cdpPort": 38818

Chrome version: 131.0.6778.205

Chrome start with grok page but than nothing happening. I try to close chrome but nothing change

**Comment by JoakimCh** [comment]
Your Node version seems a bit old since it complains about the Fetch API being experimental, but I don't think that's the issue though.

Which operating system are you on? Did you try to check the "task manager" to see if Chrome is already running? If it is then try to force quit it and run the archiver again to see if it now can connect.

I have a newer version of the archiver that I'm about to release by the way, maybe I'll do it later today or tomorrow, maybe I have fixed a bug there which will help (since I've done multiple changes).

Edit: Cool to see a user of my software by the way, I NEVER got any feedback until now...

**Comment by RoccoNatuzzi** [comment]
Operating system: Windows 11
Update node to version 22.12.0
On task manager there is not chrome process

Same error

**Comment by JoakimCh** [comment]
Thanks, I think I figured it out. Planning on releasing patch tomorrow.

**Comment by RoccoNatuzzi** [comment]
ok wait for it and retry

**Comment by JoakimCh** [comment]
Thanks for the patience. I uploaded a new version, ensure it says:
```
Using grok-archiver version: 0.9.4
```
when running it. I think that should solve the problem.

**Comment by RoccoNatuzzi** [comment]
I try but nothing change.
version: 0.9.4
console log: Using grok-archiver version: 0.9.4
Using archive directory: <path>
Images archived: 0.
Connecting to the Chrome DevTools Protocol...
Could not connect. This usually means that your browser was already running (but without having the CDP port set). If that's the case just close it and run this program again, it will then launch it for you with the correct CDP port configured.

On url http://localhost:37792/json/version (Chrome open by command) see this:
{
   "Browser": "Chrome/131.0.6778.205",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
   "V8-Version": "13.1.201.19",
   "WebKit-Version": "537.36 (@81b36b9535e3e3b610a52df3da48cd81362ec860)",
   "webSocketDebuggerUrl": "ws://localhost:37792/devtools/browser/845d472b-c737-4743-9871-39fbabf25ea2"
}

37792 is port configured in json config file

**Comment by JoakimCh** [comment]
I did not have the same problem on Windows, but now I have improved the error message which will be thrown and it should contain more info about what's happening. So try again with 0.9.5 and give me the output. Hopefully I'll figure it out then.

**Comment by RoccoNatuzzi** [comment]
Ok, with Chrome correctly close i receive this error log:
Using grok-archiver version: 0.9.5
Using archive directory: <path>
Images archived: 0.
Connecting to the Chrome DevTools Protocol...
file:///<path>/AppData/Local/npm-cache/_npx/2c2cae5ff4585187/node_modules/jlc-cdp/jlc-cdp.js:276
      resolve(stderr)
      ^

ReferenceError: resolve is not defined
    at Socket.stderrHandler (file:///<path>/AppData/Local/npm-cache/_npx/2c2cae5ff4585187/node_modules/jlc-cdp/jlc-cdp.js:276:7)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)

Node.js v22.12.0

**Comment by JoakimCh** [comment]
I see that I did a mistake when updating the jlc-cdp library to improve the error message. Hence the "resolve is not defined" was a new bug that I just introduced. I have now updated jlc-cdp and here `npx grok-archiver` seems to have pulled this updated dependency. But if you keep getting that "resolve is not defined" error then I guess I should push a new version of grok-archiver that force the use of the latest library.

**Comment by RoccoNatuzzi** [comment]
Same error. No new version pulled when execute command. Think a new version is needed

**Comment by JoakimCh** [comment]
Ok, 0.9.6 is live then.

**Comment by RoccoNatuzzi** [comment]
Ok there is an error stack trace:
Connecting to the Chrome DevTools Protocol...
Error: Can't connect to the DevTools protocol.
    at initChrome (file:///path/AppData/Local/npm-cache/_npx/2c2cae5ff4585187/node_modules/jlc-cdp/jlc-cdp.js:305:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async connectToChrome (file:///path/AppData/Local/npm-cache/_npx/2c2cae5ff4585187/node_modules/archivers-common/archivers-common.js:124:22)
    at async initializeIntercept (file:///path/AppData/Local/npm-cache/_npx/2c2cae5ff4585187/node_modules/archivers-common/archivers-common.js:136:60) {
  stdout: '',
  stderr: '\r\n' +
    'DevTools listening on ws://127.0.0.1:37792/devtools/browser/126124ee-0c68-4820-b4f2-daa424488848\r\n',
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:13484:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async initChrome (file:///path/AppData/Local/npm-cache/_npx/2c2cae5ff4585187/node_modules/jlc-cdp/jlc-cdp.js:295:24)
      at async connectToChrome (file:///path/AppData/Local/npm-cache/_npx/2c2cae5ff4585187/node_modules/archivers-common/archivers-common.js:124:22)
      at async initializeIntercept (file:///path/AppData/Local/npm-cache/_npx/2c2cae5ff4585187/node_modules/archivers-common/archivers-common.js:136:60) {
    [cause]: Error: connect ECONNREFUSED ::1:37792
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 37792
    }
  }
}
Could not connect. This usually means that your browser was already running (but without having the CDP port set). If that's the case just close it and run this program again, it will then launch it for you with the correct CDP port configured.

**Comment by JoakimCh** [comment]
Interesting!

On your computer "localhost" resolves to ::1 (the IPv6 loopback address), but Chrome is not running any IPv6 server (only an IPv4), hence the connection was refused.

I easily fixed this by using the explicit IPv4 loopback address of 127.0.0.1 in my code instead.

I think now it should work!

EDIT: v0.9.7

**Comment by RoccoNatuzzi** [comment]
Ok finally works! Thanks!
